export type ErrorType = "INVALID_FIELD_VALUE" | "FAILED_CAPTCHA" | "FAILED_CONNECTION" | "FAILED_INQUIRY_SENDING" | "FAILED_REPLY_SENDING" | "REACHED_RATE_LIMIT";

export type ErrorContentType = "NAME" | "EMAIL" | "SUBJECT" | "MESSAGE" | "IP" | "GLOBAL";
